workflows:
  clawwatch-workflow:
    name: ClawWatch Build & Deploy
    max_build_duration: 60
    instance_type: mac_mini_m2
    
    environment:
      xcode: latest
      vars:
        BUNDLE_ID: "com.dsumm.clawwatch.watchkitapp"
        TEAM_ID: "J7W6QJ77XW"
      
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: master
          include: true
    
    scripts:
      - name: Install XcodeGen
        script: brew install xcodegen
        
      - name: Generate Xcode project
        script: xcodegen generate
        
      - name: Build watchOS app (no signing)
        script: |
          xcodebuild build \
            -project ClawWatch.xcodeproj \
            -scheme "ClawWatch Watch App" \
            -destination 'generic/platform=watchOS' \
            -configuration Release \
            CODE_SIGNING_ALLOWED=NO
            
    artifacts:
      - "*.log"
