name: ClawWatch
options:
  bundleIdPrefix: com.dsumm
  deploymentTarget:
    watchOS: "10.0"

settings:
  base:
    DEVELOPMENT_TEAM: J7W6QJ77XW
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"

targets:
  ClawWatch Watch App:
    type: application
    platform: watchOS
    sources:
      - path: "WatchGram Watch App"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.dsumm.clawwatch
        PRODUCT_NAME: ClawWatch
        INFOPLIST_FILE: "WatchGram Watch App/Info.plist"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_VERSION: "5.9"
        CODE_SIGN_STYLE: Automatic
        ENABLE_PREVIEWS: YES
        GENERATE_INFOPLIST_FILE: NO
        SUPPORTS_MACCATALYST: NO
        WATCHOS_DEPLOYMENT_TARGET: "10.0"
    info:
      path: "WatchGram Watch App/Info.plist"
      properties:
        CFBundleDisplayName: ClawWatch
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        WKApplication: true
        WKRunsIndependentlyOfCompanionApp: true
        NSSpeechRecognitionUsageDescription: "ClawWatch needs speech recognition to convert your voice to text messages for your AI assistant."
        NSMicrophoneUsageDescription: "ClawWatch needs microphone access to record your voice messages."
